### ISSUE TITLE
Double destruction causes SIGFAULT.

### ISSUE THREAD

**Issue by mishaglik** [XDLoLiK/DedProjects#1]
If we construct stack. And two times call destructor it will cause sigfault. Please add controlling this situation.
```
int main(void)
{
    Stack_t(stack);
    StackDtor(&stack);
    StackDtor(&stack);
    return 0;
}
```

**Comment by XDLoLiK** [comment]
Thanks, solved by adding an extra assert to the dtor fucnction (no poison pointers anymore)
